# Generated by Django 4.0.3 on 2022-04-07 19:10

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_liked_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(default='Like', max_length=10, verbose_name=random.Random.choices),
        ),
    ]
